name: Publishing

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0

      - name: Setup Node
        uses: actions/setup-node@v3.6.0
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org

      - name: Install
        run: npm ci

      - name: Build
        run: npm run build

      - name: Publishing
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
